### ISSUE TITLE
Add more code examples for naming guidelines

### ISSUE THREAD

**Issue by akoshelev** [PressReader/code-conventions#3]
I think we need to provide an example for every naming rule we have in our naming guidelines. As developers we're working mostly with code and IMHO code examples better explain the rule they were provided for. 

What do you think?

**Comment by eugene-kartsev** [comment]
I believe we need more examples in general. Developers are pretty lazy, it is simpler for us to reed the code rather than plain text.

**Comment by eugene-kartsev** [comment]
BTW, what do you think about adding 'wrong' examples? Now we have only 'right' examples and in some cases it might be confusing if my code follows standard or not.

**Comment by akoshelev** [comment]
My opinion is we must have both for the same reasons @eugene-kartsev described.

**Comment by maxbrodin** [comment]
@akoshelev @eugene-kartsev Added examples for naming conventions. Please check.

**Comment by eugene-kartsev** [comment]
I'm not sure about the following line:

**DO NOT** use underscore as variable name. This is incorrect:
task.ContinueWith((_) => _activeTasks.Release());

What would you like to see here? I mean if method accepts _Action&lt;Something&gt;_ and you want to use it as _Action_ (void)? In many languages single underscore means - missing or unused parameter.

**Comment by akoshelev** [comment]
Guys, you need to move this discussion from this issue as it does not have any relation with the subject

**Comment by maxbrodin** [comment]
FIxed
